var MATING_DISTANCE = 10;
var ATTACK_DISTANCE = 10;
var BASE_MAX_SPEED = 10;
var BASE_MAX_STRENGTH = 10;
var BASE_MAX_SIGHT = 10;
var BASE_MAX_DECAY = 10;
var STARTING_POPULATION = 10;
var STARTING_COLORS_MAX = 5;